.\run1.ps1 | Out-Default
.\run2.ps1 | Out-Default
.\run3.ps1 | Out-Default
.\run4.ps1 | Out-Default
.\run5.ps1 | Out-Default
.\run6.ps1 | Out-Default
.\run7.ps1 | Out-Default
.\run8.ps1 | Out-Default
.\run9.ps1 | Out-Default
.\run10.ps1 | Out-Default